- hosts: localhost
  tasks:
    - name: Set Kubernetes context
      shell: kubectl config use-context test

    - name: Deploy application
      shell: kubectl apply -f k8s-deployment.yaml
    - name: Deploy application
      shell: kubectl apply -f k8s-service.yaml
