---
- name: Deploy Flask application to Kubernetes
  hosts: localhost
  tasks:
    - name: Set Kubernetes context
      command: kubectl config use-context test
      register: context_result
      ignore_errors: yes  # Ignore errors if context does not exist

    - name: Check if context was set successfully
      fail:
        msg: "Failed to set Kubernetes context. Ensure the context exists."
      when: context_result.rc != 0

    - name: Create deployment for Flask app
      kubernetes.core.k8s:
        kubeconfig: /home/shan/.kube/config  # Specify the path to your kubeconfig if needed
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: flask-app
            labels:
              app: flask-app
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: flask-app
            template:
              metadata:
                labels:
                  app: flask-app
              spec:
                containers:
                  - name: flask-app
                    image: sanoobshan/flask-app:v1  # Your Docker image
                    ports:
                      - containerPort: 5000

    - name: Create service for Flask app
      kubernetes.core.k8s:
        kubeconfig: /home/shan/.kube/config  # Specify the path to your kubeconfig if needed
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: flask-app
          spec:
            type: NodePort  # Change to LoadBalancer if you need an external IP
            ports:
              - port: 5000
                targetPort: 5000
                nodePort: 30000  # Optional: specify a node port if you want
            selector:
              app: flask-app
